### ISSUE TITLE
problem in Johnny 2.2

### ISSUE THREAD

**Issue by greatman12** [shinnok/johnny#109]
i am trying to crack a rar file in johnny but it  gives me conversion crashed after clicking on convert

**Comment by solardiz** [comment]
> i am trying to crack a rar file in johnny but it gives me conversion crashed after clicking on convert

Maybe it did in fact crash? What happens when you run rar2john against your RAR file from the command-line? If it crashes (how exactly?), that would be a problem with rar2john or/and with your input file rather than with Johnny. A rar2john problem would need to be reported against bleeding-jumbo rather than against Johnny. That said, maybe Johnny should be more verbose about exactly how a tool it ran crashed - e.g., report the numeric exit code value and the byte size of any output received, so that we could act upon issue reports like this.

**Comment by shinnok** [comment]
Closing this in absence of crash details (platform, log, debug, version).
