### ISSUE TITLE
Add formats found in the file to the format list

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#15]
In the attack option tab, I think it'd be a great idea to add the found hashes formats of the files in the formatList(auto-detect, des etc..). What do you think @Shinnok, is it a great idea ?

**Comment by math07** [comment]
Also, do we want.
1) To show all default formats present in the list + the new one found in the current file.
OR
2) To show only the one found in the file. The user still has the possibility to write anything he wants in the field.

**Comment by shinnok** [comment]
That would be a great thing to have. Yes, for the jumbo case, where we can get the formats, it should override the default list.
It would also be awesome if you could do an update for the core JtR formats as depicted in devnotes.txt. The hardcoded list in Johnny might be out of date. It would also be helpful if we add the hardcoded list to the dropdown widget from code, since it would be easier to update than the .ui.

**Comment by math07** [comment]
Good, I am currently working on that.

**Comment by math07** [comment]
Done in 4e52aeb

**Comment by shinnok** [comment]
Awesome!
