### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#41]
Document the Windows installer procedure. Start with the Qt Installer Framework, what did you find out, what does it produce, is it easy to rebuild?

**Comment by math07** [comment]
I followed the tutorial at https://doc.qt.io/qtinstallerframework/ifw-tutorial.html 
If we save the different xml files on git with the right folder structure, it'll be pretty easy to rebuild. The command is this : 
1) Place yourself in johhnyRelease. You'll see the config and package folders.
2) Execute this command C:\Qt\QtIFW2.0.1\bin\binarycreator.exe -c config\config.xml -p packages johnnyInstaller.exe (replace the binarycreator.exe path with the one from your computer)
3) It'll produce johnnyInstaller.exe
It is a basic installer which allows you to choose which place you want to install johnny(by default OS app_dir) and it comes bundled with 1.8.0.6-jumbo-1(the only jumbo working on windows). I think that we could let the user easily choose whether he wants to install JtR or not because there is a specifying component to install screen. (see the tutorial) (It could be checked by default and the user can choose to uncheck it.)
4) The default installer don't give option to put shortcut on desktop and launch johnny now. We have to write a small qt script for that, that's my next step.

**Comment by math07** [comment]
@shinnok Is there the notion of desktop shortcut for application on Linux or OS X ?

**Comment by shinnok** [comment]
@math07 Yes, but we don't need to worry about it, that isn't a practice on the said platforms. By the way, you only need to test the installer on Windows, you know that right?

**Comment by math07** [comment]
> By the way, you only need to test the installer on Windows, you know that right?

Oh, I wasn't sure if we need to package the johnny .dmg and jtr jumbo into an installer for OS X.

**Comment by shinnok** [comment]
There's no point in having an installer on OS X. Just the dmg package would suffice.

**Comment by math07** [comment]
Okay Shinnok, I completed the Windows Installer task.
I used the nightly build of qt installer framework since the latest release 2.0.1 was installing eveything but exiting with a crash on my windows 7 not updated VM (doesn't look professional).
Here it is https://drive.google.com/file/d/0B7lV48F7sPRdaS1adXVqdXJLWTg/view?usp=sharing
Also, I put in PR #48 the config files needed to rebuild the installer for future use.

**Comment by math07** [comment]
I didn't bundle jumbo as you said on the list.

**Comment by shinnok** [comment]
I need to test this before we can close it.

**Comment by math07** [comment]
Finally the error message from Windows Explorer with the qt installer framework on old windows 7 without any update still sometimes appears with the one build from source. It just looks "unprofessional" because johnny is installed perfectly. I don't think it's really important and we can't really do something easy about it. 
By the way, all binaries(windows and os x ) are now on the wiki.

**Comment by shinnok** [comment]
I'm not sure what crash you are talking about here, you haven't provided any details or screenshot.

**Comment by math07** [comment]
![image](https://cloud.githubusercontent.com/assets/9955284/8520959/436f9078-23ad-11e5-9161-87f621d20db1.png)
The installer finish and johnny starts correctly. Everything seems fine but Windows shows that message. Clicking on "close program" doesn't do anything since the installer already finished.

**Comment by shinnok** [comment]
Then I guess it's not our problem.

**Comment by shinnok** [comment]
- Windows : johnny2.0installer.zip
- OS X : johnny_2.0_osx.zip

Be consistent in file naming.
johnny-2.0-win.zip
johnny-2.0-osx.zip

**Comment by math07** [comment]
> Windows : johnny2.0installer.zip
> OS X : johnny_2.0_osx.zip
> Be consistent in file naming.
> johnny-2.0-win.zip
> johnny-2.0-osx.zip

Yes, it's in my TODO list, I'm trying to see how to delete file on the wiki file manager(maybe we don't have the permission?) or rename them.

**Comment by shinnok** [comment]
Tested on Windows 7 and it seems to work fine. Closed.
