### ISSUE TITLE
OS X dmg package

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#42]
I can do the initial work on Yosemite and then Mathieu can test the results on the older OS X versions.

**Comment by shinnok** [comment]
Investigate using the macdeployqt tool.
http://doc.qt.io/qt-5/osx-deployment.html

**Comment by math07** [comment]
Are you done with the .dmg ?

**Comment by shinnok** [comment]
I won't be able to do it in a timely fashion, I've got too much on my plate right now. Can you give it a quick shot? Since you're supposed to test the older OS X anyways.
I don't foresee any issues with it, it should be pretty much straightforward and way easier than the Windows one.

**Comment by math07** [comment]
Okay I'll take care of it. Is there the equivalent of DLL on os x that  
we should package in the DMG or do we release it as is ?

**Comment by shinnok** [comment]
The macdeployqt tool will bundle the necessary Qt frameworks into the .app bundle, which in turn goes into the .dmg package. See the tool's options.

**Comment by math07** [comment]
> The macdeployqt tool will bundle the necessary Qt frameworks into the .app bundle, which in turn goes into the .dmg package. See the tool's options.

All right, I'll update french translation in PR #48, rebuild the Windows installer, make the dmg based on branch beforeReleasePart2, test it on Mavericks and old Leopard(with no qt installed) this weekend.

**Comment by math07** [comment]
So far, I built a .dmg that is supposed to be architecture universal on my OS X 10.9 with 64 bits compiler because I added those lines in the johnny.pro file. It should work on 32 bits OS X according to the doc but I get wrong architecture on my Leopard 10.5 32 bits machine. 
 # To build universal binary or .dmg on OS X, uncomment this line
CONFIG += x86 ppc x86_64 ppc64
QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.5
As, an other open source project says https://github.com/supertuxkart/stk-code/issues/2063, Apple makes it hard to support old version of OS X. Anyway, I'll try to install a development environment on my Leopard 10.5 VM with no working internet connection. Maybe I'll have to use  old qt version or . I don't have access to other OS X software than those 2 vm, I read the doc but I'm not even sure the .dmg will work on 10.8 or 10.10 or powerpc etc... In fact, after reading the doc, I was pretty confident the binary would be universal with those things added to the .pro file but the tests give "wrong architecture error" on 10.5. Maybe it's because it is a 32 bits vm, maybe it's because 10.5 < 10.9, maybe it's because of both hahaha

**Comment by math07** [comment]
I think that I'd need the Mac OS X 10.5 SDK but Apple don't distribute it easily.

**Comment by math07** [comment]
You can find my current dmg from Mavericks on the openwall wiki

**Comment by shinnok** [comment]
Yeah, I'm not that sure we can use the same dmg on old versions of OS X. Just test your dmg on Mavericks, I'll do so on Yosemite and that will suffice.
The old OS X's are going to get only source building support, thus try and focus on that.

**Comment by shinnok** [comment]
The dmg package is working fine for me on a fresh install of Yosemite.

**Comment by math07** [comment]
For the records, to make a .dmg with correct title, you have to follow these exact steps.
1. Place yourself in the build directory.
2. /Users/admin/Qt5.4.1/5.4/clang_64/bin/macdeployqt Johnny.app verbose=2 -dmg

If you do the opposite, I think that you'll get wrong title in finder #67. So don't use those steps:
1. Place yourself in the directory with macdeployqt
2. ./macdeployqt /Users/admin/build-johnny-Desktop_Qt_5_4_1_clang_64bit-Release/johnny.app verbose=2 -dmg
