### ISSUE TITLE
Refactor Settings - JohnSession class

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#9]
// TODO: Group settings into separate class with support for
    //       saving and so on.

**Comment by shinnok** [comment]
More definitions regarding this task:

What we need is a wrapper class named JohnSession that encompasses all settings that define a cracking session. All values are still stored and loaded via QSettings inside the class.

Use a single johnny.ini to store all session details and other application preferences. Different sessions fall into different beginGroup() key prefixes. The .rec stay separate. We also need to split default.log for each different session.

**Comment by math07** [comment]
> What we need is a wrapper class named JohnSession that encompasses all settings that define a cracking session. All values are still stored and loaded via QSettings inside the class.

What variables do you have in mind for JohnSession ? In my mind right now, I don't see what we'll put into it because with m_setting(QSetting) in MainWindow class, we will have all our information into the SAME member variable. 
For example, the groups will make something like this :
m_setting.getValue(session/nameOfSession1/isForkEnabled); m_setting.getValue(session/nameOfSession2/isForkEnabled);
m_Setting.getValue(session/nameOfSession1/mode); 
etc..

**Comment by shinnok** [comment]
I think this one makes more sense now that we have the multiple sessions code in. Encapsulating those m_settings calls in a JohnSession class and the afferent methods has multiple advantages:

1. We get rid of ugly getValue() / setValue() calls spread all over the UI code; We do session.setMode() or session.isForkEnabled() for e.g.;
2. We start defining what an attack session is; (A name, a set of input files, JohnSession.mode(), JohnSession.isForkEnabled(), etc.. you get the idea)
3. We can pass a fully defined session around as a single variable;
4. We get to write more beautiful code, for e.g. by doing JohnSession.save() JohnSession.load() instead of iterating over lists and other data types and serializing/deserializing each and every option in the UI code.

**Comment by math07** [comment]
Will we put the things like m_pathToJohn m_timeInterval etc... into JohnSession. Are these settings really related to a session or global application settings?

**Comment by shinnok** [comment]
I just left a reply to issue #13. Let's continue there. :-)

**Comment by math07** [comment]
> We get to write more beautiful code, for e.g. by doing JohnSession.save() JohnSession.load() instead of iterating over lists and other data types and serializing/deserializing each and every option in the UI code

How could we easily achieve this requirement since we only have access to the class  Ui::MainWindow in MainWindow ?

**Comment by shinnok** [comment]
>How could we easily achieve this requirement since we only have access to the class Ui::MainWindow in MainWindow ?

Not sure what requirement you're talking about?

**Comment by math07** [comment]
Instead of having the load and save methods in MainWindow, you sais that you want to make JohnSession::save() and JohnSession::load() methods(point 4 of your message). How can we easily achieve this without access to the UI in JohnSession(Ui::MainWindow) ?

**Comment by math07** [comment]
I thought that you wanted to replace the two methods MainWindow::restoreSessionOptions() and the part of MainWindow::saveAttackParameters() who is reading the UI and saving it to a session with JohnSession::load() and JohnSession::save().  So my question was, how can we easily achieve this without access to the UI in JohnSession(Ui::MainWindow) ?

**Comment by shinnok** [comment]
JohnSession has nothing to do with the UI directly. The class's purpose is to abstract away all of the properties that define an attack as well as the code that reads and writes a session via QSettings. That class is then supposed to be used by code in MainWindow to populate the UI.

Let me know if it still doesn't make sense to you, so that you don't waste time implementing it wrong.

**Comment by math07** [comment]
Oh, I always thought about auto-always saving to Qsettings and not storing any member variables in JohnSession except the m_settings variable and the session name (given in the constructor). Is that what you want ? That's why I didn't understand why we'd need load and save methods.
QString isForkEnabled() {
return m_settings.value("isForkEnabled");
}
void setForkEnabled(bool isForkEnabled) {
m_settings.setValue("isForkEnabled", isForkEnabled);
}

**Comment by shinnok** [comment]
Auto saving was for the Settings tab only. Now that you brought the JohnSession into discussion too, I should make it clear that we should only save settings for a session when a new attack is started. Otherwise it doesn't make sense, since they won't be used by resume anyway.
We should inform the user that settings made to an existing session aren't applied until a new attack is started.

**Comment by math07** [comment]
I meant auto-saving in a way that we don't store sessions attributes(we directly access the QSettings), not in a way that we apply settings changed to current session.

**Comment by math07** [comment]
But now I understand that you want a general JohnSession with member variables m_isForkEnabled etc.. that we can play with later in the code for different reasons without saving it to QSettings (only doing so when a new attack is started).

**Comment by math07** [comment]
Also, we should never save a session under the same name because the .rec won't make sense. When john start, we always create a new session, we can't save change to an existing one.

**Comment by shinnok** [comment]
That's correct. We never save a new attack under the same session name. We also can't modify an existing session. So the only difficulty here is how do we make this obvious in the UI.
We need to be very explicit that modifying attack settings won't take effect until a new attack is started.

**Comment by shinnok** [comment]
>I meant auto-saving in a way that we don't store sessions attributes(we directly access the QSettings), not in a way that we apply settings changed to current session.

Auto saving was for the general settings in the Settings pane. JohnSession is just a normal class, with extra methods to serialize/deserialize to and from QSettings. This is on demand, by calling attack.save() and attack.load(), respectively. A session has a name and that needs to be set before calling .load(), via the constructor and/or a separate method.

**Comment by shinnok** [comment]
>So the only difficulty here is how do we make this obvious in the UI.
We need to be very explicit that modifying attack settings won't take effect until a new attack is started.

I added this clarification tip:
https://github.com/shinnok/johnny/commit/ea0a85ff18aae66eaf11487f0fde17a8d31f9975

This is all I can think of for now. Let's hold on to it until the next release and then ask users again how could we make this more clear in usability terms.

**Comment by shinnok** [comment]
Implemented.
